#! python3
# Downloads all XKCD comics

import os , requests , bs4

url = "https://xkcd.com"  # Starting URL
output_dir = "xkcd_comics"
os.makedirs(output_dir, exist_ok=True) # Store comics in ./xkcd. 

#  1) Download the page.
while not url.endswith("#"):
    print(f"Downloading page {url}...")
    res = requests.get(url)
    res.raise_for_status()

    soup = bs4.BeautifulSoup(res.text, "html.parser")
    comic_elem = soup.select("#comic img")

    # 2) Find the url of the comic image.
    if comic_elem:
        comic_url = "https:" + comic_elem[0].get("src")
        print(f"Downloading image {comic_url}...")
        res = requests.get(comic_url)
        res.raise_for_status()

        # 3) Save the image ./xkcd
        image_name = os.path.basename(comic_url)
        with open(os.path.join(output_dir, image_name), "wb") as img_file:
            img_file.write(res.content)

    prev_link = soup.select_one("a[rel='prev']")
    if prev_link:
        url = "https://xkcd.com" + prev_link.get("href")
    else:
        break

print("Done. The Download is completed!")
