#! python3
# Downloads all XKCD comics using mmultiple Threads

import os , requests , bs4

url = "https://xkcd.com"  # Starting URL
output_dir = "xkcd_comics"
os.makedirs(output_dir, exist_ok=True) # Store comics in ./xkcd. 

#  1) Download the page.
while not url.endswith("#"):
    print(f"Downloading page {url}...")
    res = requests.get(url)
    res.raise_for_status()

    soup = bs4.BeautifulSoup(res.text, "html.parser")
    comic_elem = soup.select("#comic img")

    # 2) Find the url of the comic image.
    if comic_elem:
        comic_url = "https:" + comic_elem[0].get("src")
        print(f"Downloading image {comic_url}...")
        res = requests.get(comic_url)
        res.raise_for_status()

        # 3) Save the image ./xkcd
        image_name = os.path.basename(comic_url)
        with open(os.path.join(output_dir, image_name), "wb") as img_file:
            img_file.write(res.content)

    prev_link = soup.select_one("a[rel='prev']")
    if prev_link:
        url = "https://xkcd.com" + prev_link.get("href")
    else:
        break

print("Done. The Download is completed!")
# Create and start the Thread objects
downloadThreads = []
for i in range(0, 140, 10):
    start = i
    end = i + 9
    if start == 0:
        start = 1 # There is no comic 0, so set it to 1.
    downloadThread = threading.Thread(target=downloadXkcd, args=(start,end))
    downloadThreads.append(downloadThread)
    downloadThread.start()

    # Wait for all threads to end
    for downloadThread in downloadThreads:
        downloadThread.join()
    print('Done.')
